# Generated by Django 5.1.4 on 2025-01-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='telefone',
            new_name='celular',
        ),
    ]
